apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apache-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-exporter
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: apache-exporter
      annotations:
        sumologic.com/format: "json_merge"
        sumologic.com/sourceCategory: "apache-exporter"
        sumologic.com/kubernetes_meta: "false"
        sumologic.com/exclude: "true"
    spec:
      containers:
      - name: prom-apache-exporter
        image: ghellings/apache_exporter:latest
        command: [
          "/apache_exporter/apache_exporter"
        ]
        args: [
          "-scrape_uri",
          "http://10.0.2.85:8080/server-status?auto"
        ]
        env:
          - name: KUBE_REDEPLOY
            value: "0"
        resources:          
          limits:
            memory: "20Mi"
            cpu: "50m"
          requests:
            memory: "5Mi"
            cpu: "1m"
        imagePullPolicy: Always
        ports:
        - containerPort: 9117