k8sdeploytemplatespath: "./example-configs/k8stemplates/"
k8snamespace: default
services:
  prom-exporter-apache:
    srvtype: Ec2
    srv:
      tags:
      - tag: "Product"
        value: "API"
k8slabels:
  manged: prom-exporter-mgr