k8sdeploytemplatespath: "/etc/k8s-prom-exporter-mgr/k8stemplates/"
k8snamespace: default
services:
  prom-exporter-apache:
    srvtype: Ec2
    srv:
      tags:
      - tag: "Product"
        value: "API"
k8slabels:
  managed: prom-exporter-mgr